name: Rebuild debian-*.csv

on:
  schedule:
    # Every Sunday evening
    - cron: "00 21 * * 0"

jobs:
  rebuild-debian-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref:  add_devuan

      - name: Rebuild
        timeout-minutes: 5
        run: |
          set -e
          git config user.name "watchful-0wl"
          git config user.email "watchful@tagmar.net"
          ./metascripts/rebuild-debian-csv
          git add debians-arm.csv debians-x86.csv
          if git commit -m "debians: Update Devuan/Debian/Ubuntu versions"; then
            ./metascripts/rebuild-jekyll-boards
            git add -A docs
            if git commit -m "docs: Regenerate boards"; then
              git push origin add_devuan
            fi
          fi
